### PR TITLE
Improved Mac experience; QDoubleSpinBox for BitcoinAmountField

### PR DESCRIPTION
**Pull request by p2k**
Now it can't be told if this is was a Windows App before. All Mac design principles are fulfilled and some cosmetics have been applied to suit the native look and feel.

The QDoubleSpinBox improves entering of Bitcoin amounts, no two seperate fields are required anymore. All functionality and validation effects have been retained; pressing the comma key will be internally translated to a period to keep it consistent throughout the application and ease entering in countries which use the comma as decimal separator.

### CODE REVIEW

**Comment by laanwj** [comment]
looks good..
some small comments:
- createTrayIcon: the two paths (MAC, WINDOWS) could be made more similar, resulting in less platform-specific code and more functionality; for example, it could be desirable to add Send Coins / Receive Coins / Options on windows/linux as well. The only thing that'd be different on mac is the 'QuitAction' and the separator above it. Apart from that all the addAction etc can be reused :)
- #ifdef Q_WS_MAC can be removed in gotoXXXPage(), AFAIK it's harmless to show the window when already shown
- Replacing BitcoinAmountField: great idea! I have to play with this a bit on other platforms, to see how it works there
- menubar -> now that this code has grown we should probably refactor this into a function createMenuBar similar to createTrayIcon createActions and friends
- notificator->notify(Notificator::Information, "Demo", "Demo1");  -> hey, you left in a test notification! :p

**Comment by p2k** [comment]
I agree to all your points, you even spotted my test notification (I was driving home thinking about the project when I suddenly remembered that one). Shouldn't take me long to fix those things, stay tuned.

EDIT: I've found out that the notification system doesn't work if the tray icon is hidden (too bad). I'll be looking for a workaround.

**Comment by laanwj** [comment]
But it means you tested that notification still works, even though the icon
is gone, which is good :)

**Comment by p2k** [comment]
There you go. Now Notificator got native Growl support on Mac, that might be reusable for other applications.

EDIT: Are you still busy evaluating my changes? Nearly 24h without feedback feel a bit odd :)

**Comment by p2k** [comment]
I'm continuing to polish the Mac version. I also deployed a first binary release with all dependencies bundled together.

It can be found here: https://github.com/p2k/bitcoin-qt/downloads

**Comment by laanwj** [comment]
Nice, this looks really promising. Maybe you should let Gavin Andresen know,
he's an avid Mac user.

I haven't merged it yet because I'd like to get the problems (if any arise)
with the current version resolved first. Mostly build system related crap.

Also now I'm more pushed to get Ubuntu Unity support to this level, hehe.

**Comment by p2k** [comment]
The wiki page is up with screenshots, in case you wondered how it looks like on Mac:
https://github.com/p2k/bitcoin-qt/wiki

**Comment by p2k** [comment]
This pull request was open for too long now. I'm trying to rebase, resolve possible conflicts and reopen a new pull request on the current version.

**Comment by laanwj** [comment]
Thanks! Not too much changed in the ui code, so I think rebasing will be
pretty straightforward
Op 7 okt. 2011 11:33 schreef "p2k" <
reply@reply.github.com>
het volgende:

**Comment by laanwj** [comment]
Btw no need to open a new pull rq, you can push -f to this ones branch, and
the commits will be updated automagically
Op 7 okt. 2011 11:33 schreef "p2k" <
reply@reply.github.com>
het volgende:

**Comment by p2k** [comment]
I've merged all changes into one big commit now, I hope this is ok: https://github.com/p2k/bitcoin-qt/commit/1229fa502e5daa3d3fb68dad5a339be6aa21ce65

It looks like this somehow didn't work as the old commits are still here... maybe I did something wrong.

**Comment by p2k** [comment]
Your options are to merge in my commit yourself (adding a remote to your local repository, merge and push) or I just open a new pull request. I believe it would mess up some things if you accept this old pull request.

**Comment by laanwj** [comment]
Merged, thanks!

**Comment by laanwj** [comment]
I just saw this piece of code in the growl notifier:

```
QString quotedTitle(title), quotedText(text);
quotedTitle.replace("\\", "\\\\").replace("\"", "\\");
quotedText.replace("\\", "\\\\").replace("\"", "\\");
qt_mac_execute_apple_script(script.arg(notificationApp, quotedTitle, quotedText, notificationIcon), 0);
```

As I understand it, you are quoting a string so that it can be passed on the command-line. I know from experience that at least for bash, this very tricky, and there are many sneaky way to inject commands.

Is just replacing " and \ watertight?

**Comment by p2k** [comment]
Well the first point is that title and text are provided by your/our application, so in this case you/we are more or less not trusting yourself/ourselves.

A second point is: If something goes wrong here, the message simply won't be shown, because this is "just" AppleScript which would fail to parse the line.

Finally, this piece of code first replaces \ to keep out escape sequences and then replaces " to prevent escaping the quotation. I can't think of any way to get around this (i.e. there is no ` operator like in bash or anything else).

**Pull request closed without merging**
