### PR TITLE
UTF'ization + localization

### PR DESCRIPTION
**Pull request by msva**

### CODE REVIEW

**Comment by laanwj** [comment]
thanks; I'll merge this after a bit of refactoring

**Comment by laanwj** [comment]
OK I rebased it into one big commit, and removed the changes I think are not necessarily (such as src/ui.cpp which is not used at all for qt and should be ignored) and reverted the to/fromStdString changes:

https://github.com/laanwj/bitcoin-qt/tree/unicode

Can you test and see whether it still does what it's supposed to?

**Comment by msva** [comment]
it seems to working fine, but i've found:
1) untranslated text in Options dialog (as I previously said)
2) one my mistake in russian.ts in csv saving dialog ;)

Anyway, you can commit it in main tree.

**Comment by laanwj** [comment]
Thanks, as none of those are caused by my changes, I'll merge it in. You can
submit a pull request later to fix those :)

**Pull request closed without merging**
