### PR TITLE
Made some changes to the GUI

### PR DESCRIPTION
**Pull request by Matoking**
- When the main window is maximized on Windows the translucent background is turned off (aka the background is light gray). Makes it more readable since the background isn't dark like it normally is.
- When you minimized the main window and tried to bring it up again from the taskbar the window would have been empty. This has been fixed.
- Tray icon now brings up the main window after double click (formerly it was QSystemTrayIcon::Trigger, now it's QSystemTrayIcon::DoubleClick)

### CODE REVIEW

**Comment by laanwj** [comment]
Thanks for the pull request, I do have some questions:
- It should be possible to select/copy the text (balances etc) in the main overview page. I'm not sure why you disabled this? (TextInteractionflag:none)
- Why change bringing up main window after double-clicking instead of single-clicking on system tray icon?

**Comment by laanwj** [comment]
- before setting translucency-related parameters, it should check "QtWin::isCompositionEnabled()", because for windows xp it won't work and will be really ugly otherwise
- maybe we could merge all windows-related stuff into one method? this could save some clutter... for example, merging both the QtWin stuff from bitcoin.cpp and bitcoingui.cpp into one method in BitcoinGui that checks isMaximized() and sets parameters accordingly. This method should be called immediately after construction and on a ChangeEvent.

**Comment by Matoking** [comment]
1. Oh, I wasn't aware of that. I just thought of it as a text label that wasn't supposed to be selectable
2. The comment above said so. I guess it's out-of-date, in which case it should be changed to 
   // Click on system tray icon triggers "open bitcoin"

**Comment by Matoking** [comment]
The Windows-specific method sounds good. I'm not up for coding it right now, it's almost 12 PM here. :)

Sorry for any caused headache, I've been doing mostly Symbian-related stuff so the desktop portion of Qt is still somewhat new for me.

**Comment by laanwj** [comment]
Heh, no problem, I'm happy that you're trying to help.

Btw "git commit --amend" (or "rebase -i HEAD~3") is your friend if you
accidentally add/remove files or have other things you'd rather hide in the
history :)

**Comment by laanwj** [comment]
merged, thanks!

**Pull request closed without merging**
